facial_feature = input("A facial feature: ")
internal_organ = input("Name a internal organ: ")
household_chore = input("Name a household chore: ")
animal_name = input("Name a animal: ")
type_of_dance = input("Name a type of dance: ")
piece_of_hardware = input("Name a piece of hardware: ")
fruit = input("name of fruit: ")
art_material = input("name a art material: ")
cleaning_product = input("name a cleaning product: ")
automotive_product = input("name a automotive product: ")
verb = input("Give me a verb: ")
medical_test = input("Name a medical test: ")
emotion = input("Name a emotion: ")
name_of_room = input("Name of a room: ")
girl_names = input("A funny girls name: ")
boy_names = input("A funny boys name: ")
musical_instrument = input("Name a musical instrument: ")
item_of_clothing = input("Name a clothing item: ")
childs_toy = input("A child's toy: ")

print("When Mary and Jim first met they knew right away they were destined to be together.")
print("Jim was immediately attracted to Mary's " + facial_feature + "and Mary loved Jim's " + internal_organ + ".")
print("So in 6 months they were engaged and planned a large " + household_chore + ".")
print("At the wedding everyone raved about the 2 " + animal_name + ".")
print("The highlight of the evening was the " + type_of_dance + "dancing.")
print("Before you knew it there was a" + piece_of_hardware + "in Jim's eyes.")
print("He told Mary it was time to start a " + fruit + ".")
print("After a romantic dinner of " + art_material +  "and " + cleaning_product + ", with a little " + automotive_product + "to drink, the " + verb +"began.")
print("Three weeks later Mary took a " + medical_test + "test and they discovered the " + emotion + "news - she was pregnant.")
print("Now they are busy decorating the " + name_of_room + ", picking out names such as " + girl_names + "and " + boy_names +".")
print("Most pregnant women have cravings and Mary is no exception.")
print("She has sent Jim to the store for things like a " + musical_instrument + "and a " + item_of_clothing + ".")
print("But overall the pregnancy is passing without a hitch and before you know it, the little " + childs_toy + "will enter the world.")